config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'

  resources :peices

  root 'page#home'

  get 'page/about'

  get 'page/blog'

  get 'page/gallery'

  get 'page/contact'

end

app/models/peice.rb
class Peice < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

before_action :authenticate_user!, except: [:index]

  def add
    id = params[:id]

      if session[:cart] then
        cart = session[:cart]
      else
        session[:cart] = {}
        cart = session[:cart]
      end

      if cart[id] then
        cart[id] = cart[id] + 1
      else
        cart[id] = 1
      end
    redirect_to :action => :index
  end

  def clearCart
    session[:cart] = nil
    redirect_to :action => :index
  end

  def index

    if session[:cart] then
      @cart = session[:cart]
  else
    @cart = {}
  end
end

end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def about
  end

  def blog
  end

  def gallery
  end

  def contact
  end
end

app/controllers/peices_controller.rb
class PeicesController < ApplicationController
  before_action :set_peice, only: [:show, :edit, :update, :destroy]

  # GET /peices
  # GET /peices.json
  def index
    @peices = Peice.all
  end

  # GET /peices/1
  # GET /peices/1.json
  def show
  end

  # GET /peices/new
  def new
    @peice = Peice.new
  end

  # GET /peices/1/edit
  def edit
  end

  # POST /peices
  # POST /peices.json
  def create
    @peice = Peice.new(peice_params)

    respond_to do |format|
      if @peice.save
        format.html { redirect_to @peice, notice: 'Peice was successfully created.' }
        format.json { render :show, status: :created, location: @peice }
      else
        format.html { render :new }
        format.json { render json: @peice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peices/1
  # PATCH/PUT /peices/1.json
  def update
    respond_to do |format|
      if @peice.update(peice_params)
        format.html { redirect_to @peice, notice: 'Peice was successfully updated.' }
        format.json { render :show, status: :ok, location: @peice }
      else
        format.html { render :edit }
        format.json { render json: @peice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peices/1
  # DELETE /peices/1.json
  def destroy
    @peice.destroy
    respond_to do |format|
      format.html { redirect_to peices_url, notice: 'Peice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peice
      @peice = Peice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def peice_params
      params.require(:peice).permit(:title, :description, :image_url, :price, :category, :subcategory)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/peices_helper.rb
module PeicesHelper
end

app/views/cart/index.html.erb
<h1>Your Cart</h1>

<% if @cart.empty? %>
    <p>Your Cart is Currently Empty</p>
<% else %>
    <%= link_to 'Empty your Cart', cart_clear_path %>
<% end %>
<br><br><br>

<% total = 0 %>

<ul>
<% @cart.each do | id, quantity | %>
    <% peice = Peice.find_by_id(id) %>

    <li>
        <%= link_to peice.title, peice %>
        <p><%= peice.description %></p>
        <p><%= number_to_currency(peice.price, :unit => '$') %></p>
        <p>Quantity: <%= quantity %></p>
    </li>
    <% total += quantity * peice.price %>
<% end %>

<p><b><%= number_to_currency(total, :unit => '$') %></b></p>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pizzadabs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<nav id="nav">
  <div id="page_nav">
          <%= link_to "Home", root_path %>
          <%= link_to "Boutique", peices_path %>
          <%= link_to "About", page_about_path %>
          <%= link_to "Gallery", page_gallery_path %>
          <%= link_to "Blog", page_blog_path %>
          <%= link_to "Contact", page_contact_path %>

  </div>

    <div id="sign_in">
        <% if user_signed_in? %>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% else %>
            <%= link_to "Sign In", new_user_session_path %>
            <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
  </div>
</nav>

<div id="main_wrap">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>
</div>
</body>
</html>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/blog.html.erb
<h1>Page#blog</h1>
<p>Find me in app/views/page/blog.html.erb</p>

app/views/page/contact.html.erb
<h1>Page#contact</h1>
<p>Find me in app/views/page/contact.html.erb</p>

app/views/page/gallery.html.erb
<h1>Page#gallery</h1>
<p>Find me in app/views/page/gallery.html.erb</p>

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

app/views/peices/_form.html.erb
<%= form_for(@peice) do |f| %>
  <% if @peice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@peice.errors.count, "error") %> prohibited this peice from being saved:</h2>

      <ul>
      <% @peice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :subcategory %><br>
    <%= f.text_field :subcategory %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/peices/edit.html.erb
<h1>Editing Peice</h1>

<%= render 'form' %>

<%= link_to 'Show', @peice %> |
<%= link_to 'Back', peices_path %>

app/views/peices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Peices</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Price</th>
      <th>Category</th>
      <th>Subcategory</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @peices.each do |peice| %>
      <tr>
        <td><%= peice.title %></td>
        <td><%= peice.description %></td>
        <td><%= peice.image_url %></td>
        <td><%= peice.price %></td>
        <td><%= peice.category %></td>
        <td><%= peice.subcategory %></td>
        <td><%= link_to 'Show', peice %></td>
        <td><%= link_to 'Edit', edit_peice_path(peice) %></td>
        <td><%= link_to 'Destroy', peice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><a href="/cart/<%= peice.id %>"> Add To Cart</a></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Peice', new_peice_path %>

app/views/peices/new.html.erb
<h1>New Peice</h1>

<%= render 'form' %>

<%= link_to 'Back', peices_path %>

app/views/peices/show.html.erb
<p id="notice"><%= notice %></p>
<h1>This is my product</h1>
<p>
  <strong>Title:</strong>
  <%= @peice.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @peice.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @peice.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @peice.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @peice.category %>
</p>

<p>
  <strong>Subcategory:</strong>
  <%= @peice.subcategory %>
</p>

<%= link_to 'Edit', edit_peice_path(@peice) %> |
<%= link_to 'Back', peices_path %>